<a href="https://colab.research.google.com/github/trishaladabala/Pistachio-Prediciton/blob/main/Pistachio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1) Importing the libraries

In [258]:
import pandas as pd
import numpy as np

2) Loading the Dataset

In [259]:
df = pd.read_csv('/content/Pistachio_28_Features_Dataset-Table 1.csv')

3) Encoding the non numerical features using a LabelEncoder

In [260]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Class'] = le.fit_transform(df['Class'])

4) Checking the relation between different features for optimisation

In [261]:
corr_matrix = df.corr()

In [262]:
corr_matrix.to_csv('correlation_matrix.csv')

In [263]:
df = df.drop(['Kurtosis_RB'],axis=1)
df = df.drop(['Kurtosis_RG'],axis=1)
df = df.drop(['Shapefactor_4'],axis=1)
df = df.drop(['StdDev_RG'],axis=1)

5) Spliting the dataset

In [264]:
X= df.iloc[:,:-1].values
y= df.iloc[:,-1].values

In [265]:
print(X)

[[ 6.339100e+04  1.568405e+03  3.903396e+02 ...  6.635000e-01
   7.591000e-01  2.969200e+00]
 [ 6.835800e+04  1.942187e+03  4.108594e+02 ... -2.713000e-01
  -2.927000e-01  1.980700e+00]
 [ 7.358900e+04  1.246538e+03  4.523630e+02 ... -4.500000e-01
   2.998000e-01  3.542000e+00]
 ...
 [ 1.011360e+05  1.255619e+03  4.752161e+02 ... -8.790000e-01
  -4.470000e-01  3.311200e+00]
 [ 9.740900e+04  1.195215e+03  4.521823e+02 ... -8.404000e-01
  -3.153000e-01  3.423700e+00]
 [ 7.846600e+04  2.356908e+03  4.459131e+02 ... -5.962000e-01
  -3.492000e-01  2.527800e+00]]


In [266]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

6) Scaling for better performance

In [267]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

7) Training and testing on RandomForestClassifier

In [268]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 42)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=42)

In [269]:
y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix ,accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[223  21]
 [ 27 159]]


0.8883720930232558

8) Training and testing on KNN Classifier

In [270]:
from sklearn.neighbors import KNeighborsClassifier
classifier2 = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier2.fit(X_train, y_train)

KNeighborsClassifier()

In [271]:
y_pred3 = classifier2.predict(X_test)

from sklearn.metrics import confusion_matrix ,accuracy_score
cm = confusion_matrix(y_test, y_pred3)
print(cm)
accuracy_score(y_test, y_pred3)

[[227  17]
 [ 26 160]]


0.9

9) Training and testing on a Logistic Regressor

In [272]:
from sklearn.linear_model import LogisticRegression
classifier1 = LogisticRegression(random_state = 42)
classifier1.fit(X_train, y_train)


LogisticRegression(random_state=42)

In [273]:
y_pred2 = classifier1.predict(X_test)

from sklearn.metrics import confusion_matrix ,accuracy_score
cm = confusion_matrix(y_test, y_pred2)
print(cm)
accuracy_score(y_test, y_pred2)

[[227  17]
 [ 14 172]]


0.9279069767441861

10) Building an Artificial Neural Network

In [274]:
import tensorflow as tf

In [275]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [276]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [277]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8115 - loss: 0.6055
Epoch 2/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8608 - loss: 0.4930
Epoch 3/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8595 - loss: 0.4123
Epoch 4/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8873 - loss: 0.3354
Epoch 5/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8837 - loss: 0.3141
Epoch 6/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8771 - loss: 0.3202
Epoch 7/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8977 - loss: 0.2728
Epoch 8/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8874 - loss: 0.2779
Epoch 9/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8885 - loss: 0.2868
Epoch 10/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8873 - loss: 0.2757
Epoch 11/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8901 - loss: 0.2770
Epoch 12/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy:

In [278]:
y_pred4=ann.predict(X_test)
y_pred4= (y_pred4 > 0.5)
from sklearn.metrics import confusion_matrix ,accuracy_score
cm = confusion_matrix(y_test, y_pred4)
print(cm)
accuracy_score(y_test, y_pred4)

14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step 
[[229  15]
 [  9 177]]


0.9441860465116279